//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestore) DeepCopyInto(out *DiskRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestore.
func (in *DiskRestore) DeepCopy() *DiskRestore {
	if in == nil {
		return nil
	}
	out := new(DiskRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestoreList) DeepCopyInto(out *DiskRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiskRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestoreList.
func (in *DiskRestoreList) DeepCopy() *DiskRestoreList {
	if in == nil {
		return nil
	}
	out := new(DiskRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestoreSpec) DeepCopyInto(out *DiskRestoreSpec) {
	*out = *in
	out.Target = in.Target
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestoreSpec.
func (in *DiskRestoreSpec) DeepCopy() *DiskRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(DiskRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestoreSpecTarget) DeepCopyInto(out *DiskRestoreSpecTarget) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestoreSpecTarget.
func (in *DiskRestoreSpecTarget) DeepCopy() *DiskRestoreSpecTarget {
	if in == nil {
		return nil
	}
	out := new(DiskRestoreSpecTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestoreStatus) DeepCopyInto(out *DiskRestoreStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestoreStatus.
func (in *DiskRestoreStatus) DeepCopy() *DiskRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(DiskRestoreStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskSnapshot) DeepCopyInto(out *DiskSnapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskSnapshot.
func (in *DiskSnapshot) DeepCopy() *DiskSnapshot {
	if in == nil {
		return nil
	}
	out := new(DiskSnapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskSnapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskSnapshotList) DeepCopyInto(out *DiskSnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiskSnapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskSnapshotList.
func (in *DiskSnapshotList) DeepCopy() *DiskSnapshotList {
	if in == nil {
		return nil
	}
	out := new(DiskSnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskSnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskSnapshotSpec) DeepCopyInto(out *DiskSnapshotSpec) {
	*out = *in
	out.Source = in.Source
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskSnapshotSpec.
func (in *DiskSnapshotSpec) DeepCopy() *DiskSnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(DiskSnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskSnapshotSpecSource) DeepCopyInto(out *DiskSnapshotSpecSource) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskSnapshotSpecSource.
func (in *DiskSnapshotSpecSource) DeepCopy() *DiskSnapshotSpecSource {
	if in == nil {
		return nil
	}
	out := new(DiskSnapshotSpecSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskSnapshotStatus) DeepCopyInto(out *DiskSnapshotStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskSnapshotStatus.
func (in *DiskSnapshotStatus) DeepCopy() *DiskSnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(DiskSnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskVolume) DeepCopyInto(out *DiskVolume) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskVolume.
func (in *DiskVolume) DeepCopy() *DiskVolume {
	if in == nil {
		return nil
	}
	out := new(DiskVolume)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskVolume) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskVolumeList) DeepCopyInto(out *DiskVolumeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiskVolume, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskVolumeList.
func (in *DiskVolumeList) DeepCopy() *DiskVolumeList {
	if in == nil {
		return nil
	}
	out := new(DiskVolumeList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskVolumeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskVolumeSpec) DeepCopyInto(out *DiskVolumeSpec) {
	*out = *in
	out.Resources = in.Resources
	out.Source = in.Source
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskVolumeSpec.
func (in *DiskVolumeSpec) DeepCopy() *DiskVolumeSpec {
	if in == nil {
		return nil
	}
	out := new(DiskVolumeSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskVolumeSpecImage) DeepCopyInto(out *DiskVolumeSpecImage) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskVolumeSpecImage.
func (in *DiskVolumeSpecImage) DeepCopy() *DiskVolumeSpecImage {
	if in == nil {
		return nil
	}
	out := new(DiskVolumeSpecImage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskVolumeSpecRequests) DeepCopyInto(out *DiskVolumeSpecRequests) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskVolumeSpecRequests.
func (in *DiskVolumeSpecRequests) DeepCopy() *DiskVolumeSpecRequests {
	if in == nil {
		return nil
	}
	out := new(DiskVolumeSpecRequests)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskVolumeSpecResources) DeepCopyInto(out *DiskVolumeSpecResources) {
	*out = *in
	out.Requests = in.Requests
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskVolumeSpecResources.
func (in *DiskVolumeSpecResources) DeepCopy() *DiskVolumeSpecResources {
	if in == nil {
		return nil
	}
	out := new(DiskVolumeSpecResources)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskVolumeSpecSource) DeepCopyInto(out *DiskVolumeSpecSource) {
	*out = *in
	out.Image = in.Image
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskVolumeSpecSource.
func (in *DiskVolumeSpecSource) DeepCopy() *DiskVolumeSpecSource {
	if in == nil {
		return nil
	}
	out := new(DiskVolumeSpecSource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskVolumeStatus) DeepCopyInto(out *DiskVolumeStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskVolumeStatus.
func (in *DiskVolumeStatus) DeepCopy() *DiskVolumeStatus {
	if in == nil {
		return nil
	}
	out := new(DiskVolumeStatus)
	in.DeepCopyInto(out)
	return out
}
