/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"

	virtualv1 "github.com/satchel9/virtualization/pkg/apis/virtual/v1"
	versioned "github.com/satchel9/virtualization/pkg/client/clientset/versioned"
	internalinterfaces "github.com/satchel9/virtualization/pkg/client/informers/externalversions/internalinterfaces"
	v1 "github.com/satchel9/virtualization/pkg/client/listers/virtual/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DiskSnapshotInformer provides access to a shared informer and lister for
// DiskSnapshots.
type DiskSnapshotInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DiskSnapshotLister
}

type diskSnapshotInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDiskSnapshotInformer constructs a new informer for DiskSnapshot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDiskSnapshotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDiskSnapshotInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDiskSnapshotInformer constructs a new informer for DiskSnapshot type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDiskSnapshotInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VirtualizationV1().DiskSnapshots(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VirtualizationV1().DiskSnapshots(namespace).Watch(context.TODO(), options)
			},
		},
		&virtualv1.DiskSnapshot{},
		resyncPeriod,
		indexers,
	)
}

func (f *diskSnapshotInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDiskSnapshotInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *diskSnapshotInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&virtualv1.DiskSnapshot{}, f.defaultInformer)
}

func (f *diskSnapshotInformer) Lister() v1.DiskSnapshotLister {
	return v1.NewDiskSnapshotLister(f.Informer().GetIndexer())
}
