/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	virtualv1 "github.com/satchel9/virtualization/pkg/apis/virtual/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDiskSnapshots implements DiskSnapshotInterface
type FakeDiskSnapshots struct {
	Fake *FakeVirtualizationV1
	ns   string
}

var disksnapshotsResource = schema.GroupVersionResource{Group: "virtualization.matrix.io", Version: "v1", Resource: "disksnapshots"}

var disksnapshotsKind = schema.GroupVersionKind{Group: "virtualization.matrix.io", Version: "v1", Kind: "DiskSnapshot"}

// Get takes name of the diskSnapshot, and returns the corresponding diskSnapshot object, and an error if there is any.
func (c *FakeDiskSnapshots) Get(ctx context.Context, name string, options v1.GetOptions) (result *virtualv1.DiskSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(disksnapshotsResource, c.ns, name), &virtualv1.DiskSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskSnapshot), err
}

// List takes label and field selectors, and returns the list of DiskSnapshots that match those selectors.
func (c *FakeDiskSnapshots) List(ctx context.Context, opts v1.ListOptions) (result *virtualv1.DiskSnapshotList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(disksnapshotsResource, disksnapshotsKind, c.ns, opts), &virtualv1.DiskSnapshotList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &virtualv1.DiskSnapshotList{ListMeta: obj.(*virtualv1.DiskSnapshotList).ListMeta}
	for _, item := range obj.(*virtualv1.DiskSnapshotList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested diskSnapshots.
func (c *FakeDiskSnapshots) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(disksnapshotsResource, c.ns, opts))

}

// Create takes the representation of a diskSnapshot and creates it.  Returns the server's representation of the diskSnapshot, and an error, if there is any.
func (c *FakeDiskSnapshots) Create(ctx context.Context, diskSnapshot *virtualv1.DiskSnapshot, opts v1.CreateOptions) (result *virtualv1.DiskSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(disksnapshotsResource, c.ns, diskSnapshot), &virtualv1.DiskSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskSnapshot), err
}

// Update takes the representation of a diskSnapshot and updates it. Returns the server's representation of the diskSnapshot, and an error, if there is any.
func (c *FakeDiskSnapshots) Update(ctx context.Context, diskSnapshot *virtualv1.DiskSnapshot, opts v1.UpdateOptions) (result *virtualv1.DiskSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(disksnapshotsResource, c.ns, diskSnapshot), &virtualv1.DiskSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskSnapshot), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDiskSnapshots) UpdateStatus(ctx context.Context, diskSnapshot *virtualv1.DiskSnapshot, opts v1.UpdateOptions) (*virtualv1.DiskSnapshot, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(disksnapshotsResource, "status", c.ns, diskSnapshot), &virtualv1.DiskSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskSnapshot), err
}

// Delete takes name of the diskSnapshot and deletes it. Returns an error if one occurs.
func (c *FakeDiskSnapshots) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(disksnapshotsResource, c.ns, name, opts), &virtualv1.DiskSnapshot{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDiskSnapshots) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(disksnapshotsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &virtualv1.DiskSnapshotList{})
	return err
}

// Patch applies the patch and returns the patched diskSnapshot.
func (c *FakeDiskSnapshots) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *virtualv1.DiskSnapshot, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(disksnapshotsResource, c.ns, name, pt, data, subresources...), &virtualv1.DiskSnapshot{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskSnapshot), err
}
