/*
Copyright 2023 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	virtualv1 "github.com/satchel9/virtualization/pkg/apis/virtual/v1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDiskRestores implements DiskRestoreInterface
type FakeDiskRestores struct {
	Fake *FakeVirtualizationV1
	ns   string
}

var diskrestoresResource = schema.GroupVersionResource{Group: "virtualization.matrix.io", Version: "v1", Resource: "diskrestores"}

var diskrestoresKind = schema.GroupVersionKind{Group: "virtualization.matrix.io", Version: "v1", Kind: "DiskRestore"}

// Get takes name of the diskRestore, and returns the corresponding diskRestore object, and an error if there is any.
func (c *FakeDiskRestores) Get(ctx context.Context, name string, options v1.GetOptions) (result *virtualv1.DiskRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(diskrestoresResource, c.ns, name), &virtualv1.DiskRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskRestore), err
}

// List takes label and field selectors, and returns the list of DiskRestores that match those selectors.
func (c *FakeDiskRestores) List(ctx context.Context, opts v1.ListOptions) (result *virtualv1.DiskRestoreList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(diskrestoresResource, diskrestoresKind, c.ns, opts), &virtualv1.DiskRestoreList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &virtualv1.DiskRestoreList{ListMeta: obj.(*virtualv1.DiskRestoreList).ListMeta}
	for _, item := range obj.(*virtualv1.DiskRestoreList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested diskRestores.
func (c *FakeDiskRestores) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(diskrestoresResource, c.ns, opts))

}

// Create takes the representation of a diskRestore and creates it.  Returns the server's representation of the diskRestore, and an error, if there is any.
func (c *FakeDiskRestores) Create(ctx context.Context, diskRestore *virtualv1.DiskRestore, opts v1.CreateOptions) (result *virtualv1.DiskRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(diskrestoresResource, c.ns, diskRestore), &virtualv1.DiskRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskRestore), err
}

// Update takes the representation of a diskRestore and updates it. Returns the server's representation of the diskRestore, and an error, if there is any.
func (c *FakeDiskRestores) Update(ctx context.Context, diskRestore *virtualv1.DiskRestore, opts v1.UpdateOptions) (result *virtualv1.DiskRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(diskrestoresResource, c.ns, diskRestore), &virtualv1.DiskRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskRestore), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDiskRestores) UpdateStatus(ctx context.Context, diskRestore *virtualv1.DiskRestore, opts v1.UpdateOptions) (*virtualv1.DiskRestore, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(diskrestoresResource, "status", c.ns, diskRestore), &virtualv1.DiskRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskRestore), err
}

// Delete takes name of the diskRestore and deletes it. Returns an error if one occurs.
func (c *FakeDiskRestores) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(diskrestoresResource, c.ns, name, opts), &virtualv1.DiskRestore{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDiskRestores) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(diskrestoresResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &virtualv1.DiskRestoreList{})
	return err
}

// Patch applies the patch and returns the patched diskRestore.
func (c *FakeDiskRestores) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *virtualv1.DiskRestore, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(diskrestoresResource, c.ns, name, pt, data, subresources...), &virtualv1.DiskRestore{})

	if obj == nil {
		return nil, err
	}
	return obj.(*virtualv1.DiskRestore), err
}
