//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestore) DeepCopyInto(out *DiskRestore) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestore.
func (in *DiskRestore) DeepCopy() *DiskRestore {
	if in == nil {
		return nil
	}
	out := new(DiskRestore)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskRestore) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestoreList) DeepCopyInto(out *DiskRestoreList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DiskRestore, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestoreList.
func (in *DiskRestoreList) DeepCopy() *DiskRestoreList {
	if in == nil {
		return nil
	}
	out := new(DiskRestoreList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DiskRestoreList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestoreSpec) DeepCopyInto(out *DiskRestoreSpec) {
	*out = *in
	out.Target = in.Target
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestoreSpec.
func (in *DiskRestoreSpec) DeepCopy() *DiskRestoreSpec {
	if in == nil {
		return nil
	}
	out := new(DiskRestoreSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestoreSpecTarget) DeepCopyInto(out *DiskRestoreSpecTarget) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestoreSpecTarget.
func (in *DiskRestoreSpecTarget) DeepCopy() *DiskRestoreSpecTarget {
	if in == nil {
		return nil
	}
	out := new(DiskRestoreSpecTarget)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiskRestoreStatus) DeepCopyInto(out *DiskRestoreStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiskRestoreStatus.
func (in *DiskRestoreStatus) DeepCopy() *DiskRestoreStatus {
	if in == nil {
		return nil
	}
	out := new(DiskRestoreStatus)
	in.DeepCopyInto(out)
	return out
}
