// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1 "virtualization/pkg/client/clientset/versioned/typed/virtualization.matrix.io/v1"

	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeVirtualizationV1 struct {
	*testing.Fake
}

func (c *FakeVirtualizationV1) DiskRestores(namespace string) v1.DiskRestoreInterface {
	return &FakeDiskRestores{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeVirtualizationV1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
