// Code generated by informer-gen. DO NOT EDIT.

package v1

import (
	"context"
	time "time"
	virtualizationmatrixiov1 "virtualization/pkg/apis/virtualization.matrix.io/v1"
	versioned "virtualization/pkg/client/clientset/versioned"
	internalinterfaces "virtualization/pkg/client/informers/externalversions/internalinterfaces"
	v1 "virtualization/pkg/client/listers/virtualization.matrix.io/v1"

	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DiskRestoreInformer provides access to a shared informer and lister for
// DiskRestores.
type DiskRestoreInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.DiskRestoreLister
}

type diskRestoreInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDiskRestoreInformer constructs a new informer for DiskRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDiskRestoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDiskRestoreInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDiskRestoreInformer constructs a new informer for DiskRestore type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDiskRestoreInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VirtualizationV1().DiskRestores(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.VirtualizationV1().DiskRestores(namespace).Watch(context.TODO(), options)
			},
		},
		&virtualizationmatrixiov1.DiskRestore{},
		resyncPeriod,
		indexers,
	)
}

func (f *diskRestoreInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDiskRestoreInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *diskRestoreInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&virtualizationmatrixiov1.DiskRestore{}, f.defaultInformer)
}

func (f *diskRestoreInformer) Lister() v1.DiskRestoreLister {
	return v1.NewDiskRestoreLister(f.Informer().GetIndexer())
}
